services:
  - type: web
    name: pm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    rootDir: backend

  - type: web
    name: pm-frontend
    env: node
    rootDir: frontend 
    buildCommand: "pnpm install && pnpm build"
    startCommand: "pnpm start"
    autoDeploy: true